name: prime-certify
license: MIT

dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-matches
  - -Wno-name-shadowing
  - -Wno-type-defaults

library:
  source-dirs: src

executables:
  prime-certify:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - prime-certify
